#!/usr/bin/env python

import i3ipc

from nobar.window_management import (
    collect_all_windows,
    rofi_choose_between_dict_by_value,
)

if __name__ == "__main__":
    # create variables and library objects
    i3 = i3ipc.Connection()
    tree = i3.get_tree()
    visited_containers = set()
    windows = {}

    # make the windows dict contain all the windows (titles in lowercase)
    collect_all_windows(
        tree,
        windows,
        visited_containers,
        value_lambda=lambda x: x.window_title.lower(),
    )

    # exclude the focused window
    focused = tree.find_focused()
    if focused.id in windows:
        # dont bother offering to switch to the currently focused window
        windows.pop(focused.id)

    # interactively choose between the available window titles
    window_id = rofi_choose_between_dict_by_value(windows)

    # focus the chosen title
    i3.command(f'[con_id="{window_id}"] focus')
